export const CHANGE_GET_PAGES_STATUS = 'CHANGE_GET_PAGES_STATUS'
export const UPDATE_PAGES = 'UPDATE_PAGES'
export const CLEAR_PAGES = 'CLEAR_PAGES'

export const CHANGE_GET_ARTICLE_STATUS = 'CHANGE_GET_ARTICLE_STATUS'
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE'
